apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-microservice-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - sample-microservice.prod.delphi-apps.example.com
      secretName: sample-microservice-tls
  rules:
    - host: sample-microservice.prod.delphi-apps.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-microservice-service
                port:
                  number: 80
