apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-microservice-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azure-disk-standard
  resources:
    requests:
      storage: 2Gi
